### ISSUE TITLE
Cannot install with python3

### ISSUE THREAD

**Issue by kristho91** [pyg3t/pyg3t#31]
It's currently not possible to run "python3 setup.py install".

**Comment by kristho91** [comment]
I have created a diff, don't know if this is the right way to submit it - if not, please tell me :)

http://kristhomsen.dk/stuff/patch_issue31_1.diff

**Comment by askhl** [comment]
Thank you, Kris.  It appears that you have resolved the problem so you can
install it properly.  The diff is fine; will apply it once we manage to
find some time.

Best regards
Ask

2015-09-18 21:55 GMT+02:00 Kris Thomsen <notifications@github.com>:

**Comment by askhl** [comment]
(I don't know where these e-mails go exactly, so hereby a more clearly
targeted reply)

2015-09-19 16:00 GMT+02:00 Ask Hjorth Larsen <asklarsen@gmail.com>:

**Comment by KennethNielsen** [comment]
Hallo @kristho91 

This looks great. Since we moved to github, the "proper" way to submit your work would be by cloning the repository, doing your work in a branch and creating a pull request for it. However, we are also happy to do that for you.

Regarding the actual diff it seems that (besides from style fixes) the main thing fixed is the syntax concerning exceptions. Obviously fixing these is a necessary step towards supporting Python 3, but I should mention that I am not convinced this is all that is required for pyg3t to actually work the way it is supposed to. Since we actually deal quite a lot with text, and there was the big unicode change in python, there may be more subtle bugs hiding away, like e.g. how we open the files we work on. So as far as using pyg3t with python 3, so far, your milage may vary. It is however, definitely a goal to make it work. I'm a big py3 fan ;)

**Comment by kristho91** [comment]
@KennethNielsen,
I guess you're right ;) 

No, my changes are not enough, just a bit in the right direction. And at least it doesn't throw errors allover the place now - except when you actually try to run any of the tools included :)

**Comment by KennethNielsen** [comment]
It is the plan that I will start to work on this soonish, so hopefully we will see some py3 support soon.

**Comment by askhl** [comment]
pyg3t should now be fully Python3 compatible.

**Comment by askhl** [comment]
Closing.  If there's any trouble on any platform, please reopen or report anew.  Thanks.
