### ISSUE TITLE
pyg3t fails when python 3 is standard version

### ISSUE THREAD

**Issue by KennethNielsen** [pyg3t/pyg3t#5]
All of the pyg3t scripts use the:
#!/bin/env python
line to indicate which version of python is wishes to be executed with. This will indicate the standard version, but when distributions shift to python 3 as standard it will make pyg3t fail. It should be changed to indicate the python version directly.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-09-14T08:04:22Z
 * owner: k-nielsen81
 * assignee: k-nielsen81
 * the launchpad url was https://bugs.launchpad.net/bugs/1225318

**Comment by KennethNielsen** [comment]
(by k-nielsen81)
Hopefully fixed with revision 115. Will test at earliest convenience.

**Comment by askhl** [comment]
The people at the Python IRC channel once said that 'python' would always mean python2, and then eventually disappear.  Then one day when python2 is long gone, python might mean python3.  However their interpretation seems a bit too idealistic since there are distributions, I think, where 'python' means python3.  Anyway, closing
